### ISSUE TITLE
error:  "No such file or directory: 'video_ids.txt'"

### ISSUE THREAD

**Issue by andiconda** [youngwoo-yoon/youtube-gesture-dataset#4]
Traceback (most recent call last):
  File "download_video.py", line 186, in main
    rf = open("video_ids.txt", 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'video_ids.txt'

When I run step 1 to download the youtube video, the error happened.
what is the solution?

**Comment by youngwoo-yoon** [comment]
Download the file from https://drive.google.com/open?id=1grFWC7GBIeF2zlaOEtCWw4YgqHe3AFU-
and copy it to "./videos" directory.
