### ISSUE TITLE
Pin scenedetect < 0.6

### ISSUE THREAD

**Issue by Breakthrough** [youngwoo-yoon/youtube-gesture-dataset#8]
Hi there! I noticed you're using PySceneDetect, but haven't pinned the dependency. v0.6 is slated to include some breaking changes to improve the API usage somewhat, so I would recommend that you pin your version to < 0.6, otherwise the current source code will break once that is released.

Once v0.6 is released there will be a migration guide to help developers who wish to update to the latest API.

Thanks!

**Comment by youngwoo-yoon** [comment]
Thank you for the great library and your kind notice.
I will specify scenedetect<0.6 in requirements.txt.
